### ISSUE TITLE
Cloning an empty inventory gui results in nullpointer exception

### ISSUE THREAD

**Issue by DarkVanityOfLight** [DarkVanityOfLight/DarkModCore#3]
The error:
```kotlin
....
 [15:59:42 ERROR]: null
 org.bukkit.command.CommandException: Unhandled exception executing command 'jobs' in plugin DarkCitizens v1.0SNAPSHOT
...
at java.lang.Thread.run(Unknown Source) [?:1.8.0_232]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 9
at com.github.darkvanityoflight.recraftedcore.gui.InventoryGUI.getSlot(InventoryGUI.kt:82) ~[?:?]
at com.github.darkvanityoflight.recraftedcore.gui.InventoryGUI.clone(InventoryGUI.kt:155) ~[?:?]
at com.github.recraftedcivilizations.darkcitizens.commands.ShowJobs.onCommand(ShowJobs.kt:61) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.1.jar:git-Paper-138]
```

What I did in my code(com.github.recraftedcivilizations.darkcitizens.commands.ShowJobs.onCommand(ShowJobs.kt:61)):
```kotlin
val gui = jobGUI.clone()
```
jobGui is an empty inventory gui.

**Comment by DarkVanityOfLight** [comment]
Fixed with commit 74596bb503af26b5624c37eae92f1c83fea1e288
